# Site settings
title: Suela Palushi
description: Available For Hire!
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Suela Palushi
user_description: I'm a Product Manager with 5+ years of hands-on experience leading successful teams and digital initiatives, enthusiastically seeking my next challenge with the fearless mindset that no task is too scary nor too difficult!
user_title: Product Manager
email: suela@spalushi.com
twitter_username: SuelaPalushi
linkedin_username: suela-palushi
github_username: SuelaP
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

